version: '3.8'

services:
  tg-downloader:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: tg_downloader_bot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../:/app
    command: ["--mode", "bot"]
